# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5bb203b156b2f09e9347cba72f3837ed6ca9682122f020d9e89f2a7b5c47e0c5c85e8ed1c7806d072900f860e644ef0af5d69e5316a23aac9b4aa2fee5fd5e

test:
  secret_key_base: 87e3d83c66204015eb97d1c19aaf7ddac88688bf17558c2dcb0cf7c4ca2e5c32b7433a72c41514d3dcec19871255f62d0e8e8fc84f8731ee138a048a849f206d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
